run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

linters-settings:
  govet:
    enable-all: true
  gosec:
    excludes:
      - G101 # Hardcoded credentials (false positives on test mock constants)
